#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## ----- Auth ----- ##
# login:
#     path: /login
#     controller: App\Controller::login
#     method: POST

appTest:
  path: /test
  controller: App\Controller\Test::index